
###
@BASE_URL = http://localhost:3000/api/categories

###
GET {{BASE_URL}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM4MGMzOTdhMTE2MzRiM2ExNmI2NCIsImlhdCI6MTcwMjExOTgxMywiZXhwIjoxNzAyNzI0NjEzLCJzdWIiOiJhdXRoZW50aWNhdGlvbiJ9.sfiycdmWPkQPbJVU0dM_nlcW74o1JdinDRxc3hKQkmw

###
POST {{BASE_URL}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM4MGMzOTdhMTE2MzRiM2ExNmI2NCIsImlhdCI6MTcwMjExOTgxMywiZXhwIjoxNzAyNzI0NjEzLCJzdWIiOiJhdXRoZW50aWNhdGlvbiJ9.sfiycdmWPkQPbJVU0dM_nlcW74o1JdinDRxc3hKQkmw
Content-Type: application/json

{
  "name": "React"
}

###
PATCH  {{BASE_URL}}/65747d26489fae68ed4229f3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM4MGMzOTdhMTE2MzRiM2ExNmI2NCIsImlhdCI6MTcwMjExOTgxMywiZXhwIjoxNzAyNzI0NjEzLCJzdWIiOiJhdXRoZW50aWNhdGlvbiJ9.sfiycdmWPkQPbJVU0dM_nlcW74o1JdinDRxc3hKQkmw
Content-Type: application/json

{
  "name": "React adu"
}


###
DELETE  {{BASE_URL}}/65747d26489fae68ed4229f3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NmM4MGMzOTdhMTE2MzRiM2ExNmI2NCIsImlhdCI6MTcwMjExOTgxMywiZXhwIjoxNzAyNzI0NjEzLCJzdWIiOiJhdXRoZW50aWNhdGlvbiJ9.sfiycdmWPkQPbJVU0dM_nlcW74o1JdinDRxc3hKQkmw




