import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ToastProvider } from '@/components/providers/toaster-provider'
import { ConfettiProvider } from '@/components/providers/confetti-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: [
        {
            rel: 'icon',
            type: 'svg',
            sizes: '32x32',
            url: '/svg/banner.svg',
        },
        {
            rel: 'icon',
            type: 'svg',
            sizes: '16x16',
            url: '/svg/banner.svg',
        }
    ]
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={inter.className}>
                <ConfettiProvider />
                <ToastProvider />
                {children}
            </body>
        </html>
    )
}
